name: Update ExoFOP data
on:
  workflow_dispatch: # Triggered manually
  schedule:
    - cron: "0 0 * * 0" # Scheduled to run every Sunday at midnight (0:00)

jobs:
  build:
    runs-on: nectar

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Source Runner's Environment
        run: |
          # Add any environment setup commands here
          # For example, sourcing a virtual environment
          # source /path/to/your/virtualenv/bin/activate
          pwd
          source ~/.bash_profile
        shell: bash

      - name: Run Your Command
        run: python update_exofop_data.py |& tee data/update.log
        shell: bash

      - name: Commit and Push Changes
        run: |
          git add data/*
          git commit -m "Update TIC cache"
          git push
        env:
          # Set the GitHub token to enable pushing back to the repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cleanup
        uses: colpal/actions-clean@v1
        if: ${{ always() }} # To ensure this step runs even when earlier steps fail
